// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaekwondoBackend.Data;

#nullable disable

namespace TaekwondoBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250523014332_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaekwondoBackend.Entities.Grupa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("naziv");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Naziv");

                    b.ToTable("grupe", "public");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.GrupaUcenik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GrupaId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupa_id");

                    b.Property<Guid>("UcenikId")
                        .HasColumnType("uuid")
                        .HasColumnName("ucenik_id");

                    b.HasKey("Id");

                    b.HasIndex("UcenikId");

                    b.HasIndex("GrupaId", "UcenikId")
                        .IsUnique();

                    b.ToTable("grupa_ucenici", "public");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.Korisnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DatumPridruzivanja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_pridruzivanja");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ime");

                    b.Property<string>("Napomene")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("napomene");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Pojas")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("bijeli")
                        .HasColumnName("pojas");

                    b.Property<string>("Stanje")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("na_cekanju")
                        .HasColumnName("stanje");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefon");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("uloga");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pojas");

                    b.HasIndex("Stanje");

                    b.HasIndex("Uloga");

                    b.ToTable("korisnici", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Korisnici_Pojas", "pojas IN ('bijeli', 'zuti', 'narancasti', 'zeleni', 'plavi', 'smedi', 'crni_1_dan', 'crni_2_dan', 'crni_3_dan', 'crni_4_dan', 'crni_5_dan', 'crni_6_dan', 'crni_7_dan', 'crni_8_dan', 'crni_9_dan', 'crni_10_dan')");

                            t.HasCheckConstraint("CK_Korisnici_Stanje", "stanje IN ('aktivan', 'neaktivan', 'na_cekanju')");

                            t.HasCheckConstraint("CK_Korisnici_Uloga", "uloga IN ('administrator', 'trener', 'ucenik')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumPridruzivanja = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@admin.com",
                            Ime = "Admin",
                            Napomene = "Administrator user",
                            PasswordHash = "$2a$12$SQbY2HKI4X/1ytaMCHSGcOWVr7pWZ128jgdwhNRh41vZ7w67bhcNO",
                            Pojas = "crni_1_dan",
                            Stanje = "aktivan",
                            Telefon = "+38761234567",
                            Uloga = "administrator",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.Objava", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_url");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("naslov");

                    b.Property<DateTime>("Objavljeno")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("objavljeno");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sadrzaj");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tip");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("Objavljeno");

                    b.HasIndex("Tip");

                    b.ToTable("objave", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Objave_Tip", "tip IN ('vijesti', 'obavjestenje')");
                        });
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.Trening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lokacija");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("naziv");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<TimeSpan>("VrijemeDo")
                        .HasColumnType("interval")
                        .HasColumnName("vrijeme_do");

                    b.Property<TimeSpan>("VrijemeOd")
                        .HasColumnType("interval")
                        .HasColumnName("vrijeme_od");

                    b.HasKey("Id");

                    b.HasIndex("Datum");

                    b.HasIndex("Naziv");

                    b.ToTable("treninzi", "public");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.TreningGrupa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GrupaId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupa_id");

                    b.Property<Guid>("TreningId")
                        .HasColumnType("uuid")
                        .HasColumnName("trening_id");

                    b.HasKey("Id");

                    b.HasIndex("GrupaId");

                    b.HasIndex("TreningId", "GrupaId")
                        .IsUnique();

                    b.ToTable("trening_grupe", "public");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.TreningTrener", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TrenerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trener_id");

                    b.Property<Guid>("TreningId")
                        .HasColumnType("uuid")
                        .HasColumnName("trening_id");

                    b.HasKey("Id");

                    b.HasIndex("TrenerId");

                    b.HasIndex("TreningId", "TrenerId")
                        .IsUnique();

                    b.ToTable("trening_treneri", "public");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.GrupaUcenik", b =>
                {
                    b.HasOne("TaekwondoBackend.Entities.Grupa", "Grupa")
                        .WithMany("GrupaUcenici")
                        .HasForeignKey("GrupaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaekwondoBackend.Entities.Korisnik", "Ucenik")
                        .WithMany()
                        .HasForeignKey("UcenikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupa");

                    b.Navigation("Ucenik");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.Objava", b =>
                {
                    b.HasOne("TaekwondoBackend.Entities.Korisnik", "Autor")
                        .WithMany("AutorObjave")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.TreningGrupa", b =>
                {
                    b.HasOne("TaekwondoBackend.Entities.Grupa", "Grupa")
                        .WithMany("TreningGrupe")
                        .HasForeignKey("GrupaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaekwondoBackend.Entities.Trening", "Trening")
                        .WithMany("TreningGrupe")
                        .HasForeignKey("TreningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupa");

                    b.Navigation("Trening");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.TreningTrener", b =>
                {
                    b.HasOne("TaekwondoBackend.Entities.Korisnik", "Trener")
                        .WithMany()
                        .HasForeignKey("TrenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaekwondoBackend.Entities.Trening", "Trening")
                        .WithMany("TreningTreneri")
                        .HasForeignKey("TreningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trener");

                    b.Navigation("Trening");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.Grupa", b =>
                {
                    b.Navigation("GrupaUcenici");

                    b.Navigation("TreningGrupe");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.Korisnik", b =>
                {
                    b.Navigation("AutorObjave");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.Trening", b =>
                {
                    b.Navigation("TreningGrupe");

                    b.Navigation("TreningTreneri");
                });
#pragma warning restore 612, 618
        }
    }
}
