// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaekwondoBackend.Data;

#nullable disable

namespace TaekwondoBackend.Migrations
{
    [DbContext(typeof(TaekwondoDbContext))]
    [Migration("20250112192520_SeedBelts")]
    partial class SeedBelts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaekwondoBackend.Belts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Belts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "White",
                            SequenceNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yellow",
                            SequenceNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Green",
                            SequenceNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Blue",
                            SequenceNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Red",
                            SequenceNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Black",
                            SequenceNumber = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
