// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaekwondoBackend.Data;

#nullable disable

namespace TaekwondoBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaekwondoBackend.Entities.Korisnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DatumPridruzivanja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_pridruzivanja");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ime");

                    b.Property<string>("Napomene")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("napomene");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Pojas")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("bijeli")
                        .HasColumnName("pojas");

                    b.Property<string>("Stanje")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("na_cekanju")
                        .HasColumnName("stanje");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefon");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("uloga");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pojas");

                    b.HasIndex("Stanje");

                    b.HasIndex("Uloga");

                    b.ToTable("korisnici", t =>
                        {
                            t.HasCheckConstraint("CK_Korisnici_Pojas", "pojas IN ('bijeli', 'zuti', 'narancasti', 'zeleni', 'plavi', 'smedi', 'crni_1_dan', 'crni_2_dan', 'crni_3_dan', 'crni_4_dan', 'crni_5_dan', 'crni_6_dan', 'crni_7_dan', 'crni_8_dan', 'crni_9_dan', 'crni_10_dan')");

                            t.HasCheckConstraint("CK_Korisnici_Stanje", "stanje IN ('aktivan', 'neaktivan', 'na_cekanju')");

                            t.HasCheckConstraint("CK_Korisnici_Uloga", "uloga IN ('administrator', 'trener', 'ucenik')");
                        });
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.Objava", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_url");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("naslov");

                    b.Property<DateTime>("Objavljeno")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("objavljeno");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sadrzaj");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tip");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("Objavljeno");

                    b.HasIndex("Tip");

                    b.ToTable("objave", t =>
                        {
                            t.HasCheckConstraint("CK_Objave_Tip", "tip IN ('vijesti', 'obavjestenje')");
                        });
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.Objava", b =>
                {
                    b.HasOne("TaekwondoBackend.Entities.Korisnik", "Autor")
                        .WithMany("AutorObjave")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("TaekwondoBackend.Entities.Korisnik", b =>
                {
                    b.Navigation("AutorObjave");
                });
#pragma warning restore 612, 618
        }
    }
}
